services:
  backend:
    build: ./backend
    container_name: backend
    environment:
      - PORT=4000
      - DB_URI=mongodb://mongo:27017/sw1-parcial2
      - SECRET_KEY=mySecretKey
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    environment:
      - VITE_API_URL=http://localhost:4000/api
      - VITE_SOCKET_URL=http://localhost:4000
      - VITE_BASE_URL=/
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app   # Solo copia el código fuente, no el directorio node_modules
    networks:
      - app-network

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
