services:
  backend:
    build: ./backend
    container_name: backend
    environment:
      - PORT=4000
      - DB_URI=mongodb+srv://sw1:marco@cluster0.uodlpmi.mongodb.net/?retryWrites=true&w=majority
      - SECRET_KEY=mySecretKey
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules # Asegura que no copie node_modules local
    networks:
      - app-network
    restart: always  # Asegura que el contenedor esté siempre activo

  frontend:
    build: ./frontend
    container_name: frontend
    environment:
      - VITE_API_URL=http://localhost:4000/api
      - VITE_SOCKET_URL=http://localhost:4000
      - VITE_BASE_URL=/
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app  # Monta el código fuente
      - /usr/src/app/node_modules  # Volumen anónimo para node_modules
    networks:
      - app-network
    restart: always  # Asegura que el contenedor esté siempre activo

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
